//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaEco.Client.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SeaEco.Client.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MailInputText {
            get {
                return ResourceManager.GetString("MailInputText", resourceCulture);
            }
        }
        
        internal static string PasswordInputText {
            get {
                return ResourceManager.GetString("PasswordInputText", resourceCulture);
            }
        }
        
        internal static string RepPasswordInputText {
            get {
                return ResourceManager.GetString("RepPasswordInputText", resourceCulture);
            }
        }
        
        internal static string FirstNameInputText {
            get {
                return ResourceManager.GetString("FirstNameInputText", resourceCulture);
            }
        }
        
        internal static string LastNameInputText {
            get {
                return ResourceManager.GetString("LastNameInputText", resourceCulture);
            }
        }
        
        internal static string RequireElementErrorMessage {
            get {
                return ResourceManager.GetString("RequireElementErrorMessage", resourceCulture);
            }
        }
        
        internal static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        internal static string TooltipAdmin {
            get {
                return ResourceManager.GetString("TooltipAdmin", resourceCulture);
            }
        }
        
        internal static string TooltipAdminOne {
            get {
                return ResourceManager.GetString("TooltipAdminOne", resourceCulture);
            }
        }
        
        internal static string TooltipAdminTwo {
            get {
                return ResourceManager.GetString("TooltipAdminTwo", resourceCulture);
            }
        }
        
        internal static string TooltipAdminThree {
            get {
                return ResourceManager.GetString("TooltipAdminThree", resourceCulture);
            }
        }
        
        internal static string TooltipRegisterUser {
            get {
                return ResourceManager.GetString("TooltipRegisterUser", resourceCulture);
            }
        }
        
        internal static string AdminCheckboks {
            get {
                return ResourceManager.GetString("AdminCheckboks", resourceCulture);
            }
        }
        
        internal static string ActiveUserCheckboks {
            get {
                return ResourceManager.GetString("ActiveUserCheckboks", resourceCulture);
            }
        }
        
        internal static string DeactiveUserCheckboks {
            get {
                return ResourceManager.GetString("DeactiveUserCheckboks", resourceCulture);
            }
        }
        
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        internal static string ButtonAddNewUser {
            get {
                return ResourceManager.GetString("ButtonAddNewUser", resourceCulture);
            }
        }
        
        internal static string TableHeadingName {
            get {
                return ResourceManager.GetString("TableHeadingName", resourceCulture);
            }
        }
        
        internal static string TableHeadingRole {
            get {
                return ResourceManager.GetString("TableHeadingRole", resourceCulture);
            }
        }
        
        internal static string TableHeadingMail {
            get {
                return ResourceManager.GetString("TableHeadingMail", resourceCulture);
            }
        }
        
        internal static string TableHeadingStatus {
            get {
                return ResourceManager.GetString("TableHeadingStatus", resourceCulture);
            }
        }
        
        internal static string TableInputIsActive {
            get {
                return ResourceManager.GetString("TableInputIsActive", resourceCulture);
            }
        }
        
        internal static string TableInputIsNotActive {
            get {
                return ResourceManager.GetString("TableInputIsNotActive", resourceCulture);
            }
        }
        
        internal static string TableInputIsAdmin {
            get {
                return ResourceManager.GetString("TableInputIsAdmin", resourceCulture);
            }
        }
        
        internal static string TableInputIsNotAdmin {
            get {
                return ResourceManager.GetString("TableInputIsNotAdmin", resourceCulture);
            }
        }
        
        internal static string PageUserAllUsers {
            get {
                return ResourceManager.GetString("PageUserAllUsers", resourceCulture);
            }
        }
        
        internal static string PageUserNoUserFoun {
            get {
                return ResourceManager.GetString("PageUserNoUserFoun", resourceCulture);
            }
        }
        
        internal static string PageEditUserEditUser {
            get {
                return ResourceManager.GetString("PageEditUserEditUser", resourceCulture);
            }
        }
        
        internal static string PageEditUserNoUserFound {
            get {
                return ResourceManager.GetString("PageEditUserNoUserFound", resourceCulture);
            }
        }
        
        internal static string PageRegisterUserNewUser {
            get {
                return ResourceManager.GetString("PageRegisterUserNewUser", resourceCulture);
            }
        }
        
        internal static string PageCustomerNoCustomersFound {
            get {
                return ResourceManager.GetString("PageCustomerNoCustomersFound", resourceCulture);
            }
        }
        
        internal static string PageEditCustomerSuccess {
            get {
                return ResourceManager.GetString("PageEditCustomerSuccess", resourceCulture);
            }
        }
        
        internal static string PageEditCustomerFailed {
            get {
                return ResourceManager.GetString("PageEditCustomerFailed", resourceCulture);
            }
        }
    }
}
