//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaEco.Client.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SeaEco.Client.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string InputTextMail {
            get {
                return ResourceManager.GetString("InputTextMail", resourceCulture);
            }
        }
        
        internal static string InputTextPassword {
            get {
                return ResourceManager.GetString("InputTextPassword", resourceCulture);
            }
        }
        
        internal static string InputTextRepPassword {
            get {
                return ResourceManager.GetString("InputTextRepPassword", resourceCulture);
            }
        }
        
        internal static string InputTextFirstName {
            get {
                return ResourceManager.GetString("InputTextFirstName", resourceCulture);
            }
        }
        
        internal static string InputTextLastName {
            get {
                return ResourceManager.GetString("InputTextLastName", resourceCulture);
            }
        }
        
        internal static string ErrorMessageRequireElement {
            get {
                return ResourceManager.GetString("ErrorMessageRequireElement", resourceCulture);
            }
        }
        
        internal static string ErrorMessageUnexpected {
            get {
                return ResourceManager.GetString("ErrorMessageUnexpected", resourceCulture);
            }
        }
        
        internal static string TooltipAdmin {
            get {
                return ResourceManager.GetString("TooltipAdmin", resourceCulture);
            }
        }
        
        internal static string TooltipAdminOne {
            get {
                return ResourceManager.GetString("TooltipAdminOne", resourceCulture);
            }
        }
        
        internal static string TooltipAdminTwo {
            get {
                return ResourceManager.GetString("TooltipAdminTwo", resourceCulture);
            }
        }
        
        internal static string TooltipAdminThree {
            get {
                return ResourceManager.GetString("TooltipAdminThree", resourceCulture);
            }
        }
        
        internal static string TooltipRegisterUser {
            get {
                return ResourceManager.GetString("TooltipRegisterUser", resourceCulture);
            }
        }
        
        internal static string CheckboksAdmin {
            get {
                return ResourceManager.GetString("CheckboksAdmin", resourceCulture);
            }
        }
        
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        internal static string ButtonAddNewUser {
            get {
                return ResourceManager.GetString("ButtonAddNewUser", resourceCulture);
            }
        }
        
        internal static string ButtonAddNewCustomer {
            get {
                return ResourceManager.GetString("ButtonAddNewCustomer", resourceCulture);
            }
        }
        
        internal static string ButtonAddNewProject {
            get {
                return ResourceManager.GetString("ButtonAddNewProject", resourceCulture);
            }
        }
        
        internal static string TableHeadingName {
            get {
                return ResourceManager.GetString("TableHeadingName", resourceCulture);
            }
        }
        
        internal static string TableHeadingRole {
            get {
                return ResourceManager.GetString("TableHeadingRole", resourceCulture);
            }
        }
        
        internal static string TableHeadingMail {
            get {
                return ResourceManager.GetString("TableHeadingMail", resourceCulture);
            }
        }
        
        internal static string TableHeadingStatus {
            get {
                return ResourceManager.GetString("TableHeadingStatus", resourceCulture);
            }
        }
        
        internal static string TableInputIsActive {
            get {
                return ResourceManager.GetString("TableInputIsActive", resourceCulture);
            }
        }
        
        internal static string TableInputIsNotActive {
            get {
                return ResourceManager.GetString("TableInputIsNotActive", resourceCulture);
            }
        }
        
        internal static string TableInputIsAdmin {
            get {
                return ResourceManager.GetString("TableInputIsAdmin", resourceCulture);
            }
        }
        
        internal static string TableInputIsNotAdmin {
            get {
                return ResourceManager.GetString("TableInputIsNotAdmin", resourceCulture);
            }
        }
        
        internal static string TableHeaderCustomer {
            get {
                return ResourceManager.GetString("TableHeaderCustomer", resourceCulture);
            }
        }
        
        internal static string TableHeaderLocality {
            get {
                return ResourceManager.GetString("TableHeaderLocality", resourceCulture);
            }
        }
        
        internal static string TableHeaderLocalityId {
            get {
                return ResourceManager.GetString("TableHeaderLocalityId", resourceCulture);
            }
        }
        
        internal static string TableHeaderPoId {
            get {
                return ResourceManager.GetString("TableHeaderPoId", resourceCulture);
            }
        }
        
        internal static string TableHeaderProjectId {
            get {
                return ResourceManager.GetString("TableHeaderProjectId", resourceCulture);
            }
        }
        
        internal static string TableHeaderDate {
            get {
                return ResourceManager.GetString("TableHeaderDate", resourceCulture);
            }
        }
        
        internal static string TableHeaderProjectStatus {
            get {
                return ResourceManager.GetString("TableHeaderProjectStatus", resourceCulture);
            }
        }
        
        internal static string TableHeaderStatus {
            get {
                return ResourceManager.GetString("TableHeaderStatus", resourceCulture);
            }
        }
        
        internal static string TableHeaderProductionStatus {
            get {
                return ResourceManager.GetString("TableHeaderProductionStatus", resourceCulture);
            }
        }
        
        internal static string PageUserAllUsers {
            get {
                return ResourceManager.GetString("PageUserAllUsers", resourceCulture);
            }
        }
        
        internal static string PageUserNoUserFoun {
            get {
                return ResourceManager.GetString("PageUserNoUserFoun", resourceCulture);
            }
        }
        
        internal static string PageEditUserEditUser {
            get {
                return ResourceManager.GetString("PageEditUserEditUser", resourceCulture);
            }
        }
        
        internal static string PageEditUserNoUserFound {
            get {
                return ResourceManager.GetString("PageEditUserNoUserFound", resourceCulture);
            }
        }
        
        internal static string PageRegisterUserNewUser {
            get {
                return ResourceManager.GetString("PageRegisterUserNewUser", resourceCulture);
            }
        }
        
        internal static string PageCustomerCustomerList {
            get {
                return ResourceManager.GetString("PageCustomerCustomerList", resourceCulture);
            }
        }
        
        internal static string PageCustomerNoCustomersFound {
            get {
                return ResourceManager.GetString("PageCustomerNoCustomersFound", resourceCulture);
            }
        }
        
        internal static string PageCustomerInfoProjects {
            get {
                return ResourceManager.GetString("PageCustomerInfoProjects", resourceCulture);
            }
        }
        
        internal static string PageCustomerInfoCustomerInfo {
            get {
                return ResourceManager.GetString("PageCustomerInfoCustomerInfo", resourceCulture);
            }
        }
        
        internal static string PageCustomerInfoCustomerName {
            get {
                return ResourceManager.GetString("PageCustomerInfoCustomerName", resourceCulture);
            }
        }
        
        internal static string PageCustomerInfoContactPerson {
            get {
                return ResourceManager.GetString("PageCustomerInfoContactPerson", resourceCulture);
            }
        }
        
        internal static string PageCustomerInfoCustomerNumber {
            get {
                return ResourceManager.GetString("PageCustomerInfoCustomerNumber", resourceCulture);
            }
        }
        
        internal static string PageCustomerInfoDeleteCustomerSuccess {
            get {
                return ResourceManager.GetString("PageCustomerInfoDeleteCustomerSuccess", resourceCulture);
            }
        }
        
        internal static string PageCustomerInfoDeleteCustomerFailed {
            get {
                return ResourceManager.GetString("PageCustomerInfoDeleteCustomerFailed", resourceCulture);
            }
        }
        
        internal static string PageCustomerInfoNoProject {
            get {
                return ResourceManager.GetString("PageCustomerInfoNoProject", resourceCulture);
            }
        }
        
        internal static string PageEditCustomerEditCustomer {
            get {
                return ResourceManager.GetString("PageEditCustomerEditCustomer", resourceCulture);
            }
        }
        
        internal static string PageEditCustomerSuccess {
            get {
                return ResourceManager.GetString("PageEditCustomerSuccess", resourceCulture);
            }
        }
        
        internal static string PageEditCustomerFailed {
            get {
                return ResourceManager.GetString("PageEditCustomerFailed", resourceCulture);
            }
        }
        
        internal static string PageAddCustomerAddCustomer {
            get {
                return ResourceManager.GetString("PageAddCustomerAddCustomer", resourceCulture);
            }
        }
        
        internal static string PageAddCustomerSuccess {
            get {
                return ResourceManager.GetString("PageAddCustomerSuccess", resourceCulture);
            }
        }
        
        internal static string PageAddCustomerFailed {
            get {
                return ResourceManager.GetString("PageAddCustomerFailed", resourceCulture);
            }
        }
        
        internal static string PageProjectsOverviewAllProjects {
            get {
                return ResourceManager.GetString("PageProjectsOverviewAllProjects", resourceCulture);
            }
        }
        
        internal static string ButtonFilter {
            get {
                return ResourceManager.GetString("ButtonFilter", resourceCulture);
            }
        }
        
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        internal static string TableHeaderMonth {
            get {
                return ResourceManager.GetString("TableHeaderMonth", resourceCulture);
            }
        }
        
        internal static string TableHeaderYear {
            get {
                return ResourceManager.GetString("TableHeaderYear", resourceCulture);
            }
        }
        
        internal static string OptionAll {
            get {
                return ResourceManager.GetString("OptionAll", resourceCulture);
            }
        }
        
        internal static string PageLoginLogin {
            get {
                return ResourceManager.GetString("PageLoginLogin", resourceCulture);
            }
        }
        
        internal static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        internal static string ButtonForgotPassword {
            get {
                return ResourceManager.GetString("ButtonForgotPassword", resourceCulture);
            }
        }
        
        internal static string ErrorMessageMailRequired {
            get {
                return ResourceManager.GetString("ErrorMessageMailRequired", resourceCulture);
            }
        }
        
        internal static string ErrorMessageWrongMailOrPassword {
            get {
                return ResourceManager.GetString("ErrorMessageWrongMailOrPassword", resourceCulture);
            }
        }
        
        internal static string ErrorMessageWrongMail {
            get {
                return ResourceManager.GetString("ErrorMessageWrongMail", resourceCulture);
            }
        }
        
        internal static string PageResetPasswordResetPassword {
            get {
                return ResourceManager.GetString("PageResetPasswordResetPassword", resourceCulture);
            }
        }
        
        internal static string ErrorMessageToken {
            get {
                return ResourceManager.GetString("ErrorMessageToken", resourceCulture);
            }
        }
        
        internal static string ErrorMessageNoToken {
            get {
                return ResourceManager.GetString("ErrorMessageNoToken", resourceCulture);
            }
        }
        
        internal static string SuccessMessageMailSendt {
            get {
                return ResourceManager.GetString("SuccessMessageMailSendt", resourceCulture);
            }
        }
        
        internal static string PageForgotPasswordForgotPassword {
            get {
                return ResourceManager.GetString("PageForgotPasswordForgotPassword", resourceCulture);
            }
        }
        
        internal static string PageForgotPasswordHow {
            get {
                return ResourceManager.GetString("PageForgotPasswordHow", resourceCulture);
            }
        }
        
        internal static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        internal static string InputTextPositionN {
            get {
                return ResourceManager.GetString("InputTextPositionN", resourceCulture);
            }
        }
        
        internal static string InputTextPositionS {
            get {
                return ResourceManager.GetString("InputTextPositionS", resourceCulture);
            }
        }
        
        internal static string InputTextDepth {
            get {
                return ResourceManager.GetString("InputTextDepth", resourceCulture);
            }
        }
        
        internal static string InputTextMethod {
            get {
                return ResourceManager.GetString("InputTextMethod", resourceCulture);
            }
        }
        
        internal static string ButtonAddStation {
            get {
                return ResourceManager.GetString("ButtonAddStation", resourceCulture);
            }
        }
        
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        internal static string InputTextUserProjectPlan {
            get {
                return ResourceManager.GetString("InputTextUserProjectPlan", resourceCulture);
            }
        }
        
        internal static string InputTextStation {
            get {
                return ResourceManager.GetString("InputTextStation", resourceCulture);
            }
        }
        
        internal static string ButtonProjectInfoView {
            get {
                return ResourceManager.GetString("ButtonProjectInfoView", resourceCulture);
            }
        }
        
        internal static string ButtonProjectLog {
            get {
                return ResourceManager.GetString("ButtonProjectLog", resourceCulture);
            }
        }
        
        internal static string InputTextLocation {
            get {
                return ResourceManager.GetString("InputTextLocation", resourceCulture);
            }
        }
        
        internal static string InputTextLocationId {
            get {
                return ResourceManager.GetString("InputTextLocationId", resourceCulture);
            }
        }
        
        internal static string InputTextComment {
            get {
                return ResourceManager.GetString("InputTextComment", resourceCulture);
            }
        }
        
        internal static string InputTextMtb {
            get {
                return ResourceManager.GetString("InputTextMtb", resourceCulture);
            }
        }
        
        internal static string TabProjectPlan {
            get {
                return ResourceManager.GetString("TabProjectPlan", resourceCulture);
            }
        }
        
        internal static string TabProjectReport {
            get {
                return ResourceManager.GetString("TabProjectReport", resourceCulture);
            }
        }
        
        internal static string TabBStation {
            get {
                return ResourceManager.GetString("TabBStation", resourceCulture);
            }
        }
        
        internal static string InputTextNumberOfStations {
            get {
                return ResourceManager.GetString("InputTextNumberOfStations", resourceCulture);
            }
        }
        
        internal static string InputTextPlanedDate {
            get {
                return ResourceManager.GetString("InputTextPlanedDate", resourceCulture);
            }
        }
        
        internal static string PageProjectProject {
            get {
                return ResourceManager.GetString("PageProjectProject", resourceCulture);
            }
        }
        
        internal static string InputTextPoId {
            get {
                return ResourceManager.GetString("InputTextPoId", resourceCulture);
            }
        }
        
        internal static string ErrorMessageLoadingUsers {
            get {
                return ResourceManager.GetString("ErrorMessageLoadingUsers", resourceCulture);
            }
        }
        
        internal static string PageProjectsOverviewFilter {
            get {
                return ResourceManager.GetString("PageProjectsOverviewFilter", resourceCulture);
            }
        }
        
        internal static string InputTextResponsibleUser {
            get {
                return ResourceManager.GetString("InputTextResponsibleUser", resourceCulture);
            }
        }
        
        internal static string InputTextCustomerUser {
            get {
                return ResourceManager.GetString("InputTextCustomerUser", resourceCulture);
            }
        }
        
        internal static string InputTextCustomerUserTlf {
            get {
                return ResourceManager.GetString("InputTextCustomerUserTlf", resourceCulture);
            }
        }
        
        internal static string InputTextCustomerUserEmail {
            get {
                return ResourceManager.GetString("InputTextCustomerUserEmail", resourceCulture);
            }
        }
        
        internal static string InputTextFullLocation {
            get {
                return ResourceManager.GetString("InputTextFullLocation", resourceCulture);
            }
        }
        
        internal static string InputTextProductionStatus {
            get {
                return ResourceManager.GetString("InputTextProductionStatus", resourceCulture);
            }
        }
        
        internal static string TextLocationInfo {
            get {
                return ResourceManager.GetString("TextLocationInfo", resourceCulture);
            }
        }
        
        internal static string TextCusomerInfo {
            get {
                return ResourceManager.GetString("TextCusomerInfo", resourceCulture);
            }
        }
        
        internal static string TextProjectInfo {
            get {
                return ResourceManager.GetString("TextProjectInfo", resourceCulture);
            }
        }
        
        internal static string PageNewProjectNewProject {
            get {
                return ResourceManager.GetString("PageNewProjectNewProject", resourceCulture);
            }
        }
        
        internal static string ButtonExistingLocation {
            get {
                return ResourceManager.GetString("ButtonExistingLocation", resourceCulture);
            }
        }
        
        internal static string ButtonNewLocation {
            get {
                return ResourceManager.GetString("ButtonNewLocation", resourceCulture);
            }
        }
        
        internal static string InputTextStationDates {
            get {
                return ResourceManager.GetString("InputTextStationDates", resourceCulture);
            }
        }
        
        internal static string InputTextCustomer {
            get {
                return ResourceManager.GetString("InputTextCustomer", resourceCulture);
            }
        }
        
        internal static string InputTextProjectIdSe {
            get {
                return ResourceManager.GetString("InputTextProjectIdSe", resourceCulture);
            }
        }
        
        internal static string ErrorMessageLoadingCustomer {
            get {
                return ResourceManager.GetString("ErrorMessageLoadingCustomer", resourceCulture);
            }
        }
        
        internal static string ErrorMessageLoadingProject {
            get {
                return ResourceManager.GetString("ErrorMessageLoadingProject", resourceCulture);
            }
        }
        
        internal static string ButtonAddNewProjectPlan {
            get {
                return ResourceManager.GetString("ButtonAddNewProjectPlan", resourceCulture);
            }
        }
        
        internal static string PageProjectPlanNoPlan {
            get {
                return ResourceManager.GetString("PageProjectPlanNoPlan", resourceCulture);
            }
        }
        
        internal static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        internal static string ModalTextEditingProjectPlan {
            get {
                return ResourceManager.GetString("ModalTextEditingProjectPlan", resourceCulture);
            }
        }
        
        internal static string InputTextNorthDegree {
            get {
                return ResourceManager.GetString("InputTextNorthDegree", resourceCulture);
            }
        }
        
        internal static string InputTextNorthMinutes {
            get {
                return ResourceManager.GetString("InputTextNorthMinutes", resourceCulture);
            }
        }
        
        internal static string InputTextEsthDegree {
            get {
                return ResourceManager.GetString("InputTextEsthDegree", resourceCulture);
            }
        }
        
        internal static string InputTextEsthMinutes {
            get {
                return ResourceManager.GetString("InputTextEsthMinutes", resourceCulture);
            }
        }
        
        internal static string InputTextNorthCoordinates {
            get {
                return ResourceManager.GetString("InputTextNorthCoordinates", resourceCulture);
            }
        }
        
        internal static string InputTextEsthCoordinates {
            get {
                return ResourceManager.GetString("InputTextEsthCoordinates", resourceCulture);
            }
        }
        
        internal static string ButtonCreat {
            get {
                return ResourceManager.GetString("ButtonCreat", resourceCulture);
            }
        }
        
        internal static string HeaderGeneralPlanInfo {
            get {
                return ResourceManager.GetString("HeaderGeneralPlanInfo", resourceCulture);
            }
        }
        
        internal static string HeaderNewStation {
            get {
                return ResourceManager.GetString("HeaderNewStation", resourceCulture);
            }
        }
        
        internal static string ButtonAddNewStation {
            get {
                return ResourceManager.GetString("ButtonAddNewStation", resourceCulture);
            }
        }
        
        internal static string ButtonComplete {
            get {
                return ResourceManager.GetString("ButtonComplete", resourceCulture);
            }
        }
        
        internal static string ModalTextCompleteProject {
            get {
                return ResourceManager.GetString("ModalTextCompleteProject", resourceCulture);
            }
        }
        
        internal static string PageSatationOverviewNoStations {
            get {
                return ResourceManager.GetString("PageSatationOverviewNoStations", resourceCulture);
            }
        }
        
        internal static string ModalComment {
            get {
                return ResourceManager.GetString("ModalComment", resourceCulture);
            }
        }
        
        internal static string ButtonGenerateDocumentReport {
            get {
                return ResourceManager.GetString("ButtonGenerateDocumentReport", resourceCulture);
            }
        }
        
        internal static string ButtonGeneratePicturesReport {
            get {
                return ResourceManager.GetString("ButtonGeneratePicturesReport", resourceCulture);
            }
        }
        
        internal static string PageReportNoReport {
            get {
                return ResourceManager.GetString("PageReportNoReport", resourceCulture);
            }
        }
        
        internal static string PageReportDocumentsReport {
            get {
                return ResourceManager.GetString("PageReportDocumentsReport", resourceCulture);
            }
        }
        
        internal static string PageReportPicturesReport {
            get {
                return ResourceManager.GetString("PageReportPicturesReport", resourceCulture);
            }
        }
        
        internal static string InputTextWaitingForApproval {
            get {
                return ResourceManager.GetString("InputTextWaitingForApproval", resourceCulture);
            }
        }
        
        internal static string InputTextApprovedBy {
            get {
                return ResourceManager.GetString("InputTextApprovedBy", resourceCulture);
            }
        }
        
        internal static string InputTextReportType {
            get {
                return ResourceManager.GetString("InputTextReportType", resourceCulture);
            }
        }
        
        internal static string InputTextReportDateGenerated {
            get {
                return ResourceManager.GetString("InputTextReportDateGenerated", resourceCulture);
            }
        }
        
        internal static string ButtonApproved {
            get {
                return ResourceManager.GetString("ButtonApproved", resourceCulture);
            }
        }
        
        internal static string ButtonNotApproved {
            get {
                return ResourceManager.GetString("ButtonNotApproved", resourceCulture);
            }
        }
    }
}
