//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaEco.Client.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SeaEco.Client.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string InputTextMail {
            get {
                return ResourceManager.GetString("InputTextMail", resourceCulture);
            }
        }
        
        internal static string InputTextPassword {
            get {
                return ResourceManager.GetString("InputTextPassword", resourceCulture);
            }
        }
        
        internal static string InputTextRepPassword {
            get {
                return ResourceManager.GetString("InputTextRepPassword", resourceCulture);
            }
        }
        
        internal static string InputTextFirstName {
            get {
                return ResourceManager.GetString("InputTextFirstName", resourceCulture);
            }
        }
        
        internal static string InputTextLastName {
            get {
                return ResourceManager.GetString("InputTextLastName", resourceCulture);
            }
        }
        
        internal static string ErrorMessageRequireElement {
            get {
                return ResourceManager.GetString("ErrorMessageRequireElement", resourceCulture);
            }
        }
        
        internal static string ErrorMessageUnexpected {
            get {
                return ResourceManager.GetString("ErrorMessageUnexpected", resourceCulture);
            }
        }
        
        internal static string TooltipAdmin {
            get {
                return ResourceManager.GetString("TooltipAdmin", resourceCulture);
            }
        }
        
        internal static string TooltipAdminOne {
            get {
                return ResourceManager.GetString("TooltipAdminOne", resourceCulture);
            }
        }
        
        internal static string TooltipAdminTwo {
            get {
                return ResourceManager.GetString("TooltipAdminTwo", resourceCulture);
            }
        }
        
        internal static string TooltipAdminThree {
            get {
                return ResourceManager.GetString("TooltipAdminThree", resourceCulture);
            }
        }
        
        internal static string TooltipRegisterUser {
            get {
                return ResourceManager.GetString("TooltipRegisterUser", resourceCulture);
            }
        }
        
        internal static string CheckboksAdmin {
            get {
                return ResourceManager.GetString("CheckboksAdmin", resourceCulture);
            }
        }
        
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        internal static string ButtonAddNewUser {
            get {
                return ResourceManager.GetString("ButtonAddNewUser", resourceCulture);
            }
        }
        
        internal static string TableHeadingName {
            get {
                return ResourceManager.GetString("TableHeadingName", resourceCulture);
            }
        }
        
        internal static string TableHeadingRole {
            get {
                return ResourceManager.GetString("TableHeadingRole", resourceCulture);
            }
        }
        
        internal static string TableHeadingMail {
            get {
                return ResourceManager.GetString("TableHeadingMail", resourceCulture);
            }
        }
        
        internal static string TableHeadingStatus {
            get {
                return ResourceManager.GetString("TableHeadingStatus", resourceCulture);
            }
        }
        
        internal static string TableInputIsActive {
            get {
                return ResourceManager.GetString("TableInputIsActive", resourceCulture);
            }
        }
        
        internal static string TableInputIsNotActive {
            get {
                return ResourceManager.GetString("TableInputIsNotActive", resourceCulture);
            }
        }
        
        internal static string TableInputIsAdmin {
            get {
                return ResourceManager.GetString("TableInputIsAdmin", resourceCulture);
            }
        }
        
        internal static string TableInputIsNotAdmin {
            get {
                return ResourceManager.GetString("TableInputIsNotAdmin", resourceCulture);
            }
        }
        
        internal static string TableHeaderCustomer {
            get {
                return ResourceManager.GetString("TableHeaderCustomer", resourceCulture);
            }
        }
        
        internal static string TableHeaderLocality {
            get {
                return ResourceManager.GetString("TableHeaderLocality", resourceCulture);
            }
        }
        
        internal static string TableHeaderLocalityId {
            get {
                return ResourceManager.GetString("TableHeaderLocalityId", resourceCulture);
            }
        }
        
        internal static string TableHeaderPoId {
            get {
                return ResourceManager.GetString("TableHeaderPoId", resourceCulture);
            }
        }
        
        internal static string TableHeaderProjectId {
            get {
                return ResourceManager.GetString("TableHeaderProjectId", resourceCulture);
            }
        }
        
        internal static string TableHeaderDate {
            get {
                return ResourceManager.GetString("TableHeaderDate", resourceCulture);
            }
        }
        
        internal static string TableHeaderProjectStatus {
            get {
                return ResourceManager.GetString("TableHeaderProjectStatus", resourceCulture);
            }
        }
        
        internal static string TableHeaderStatus {
            get {
                return ResourceManager.GetString("TableHeaderStatus", resourceCulture);
            }
        }
        
        internal static string TableHeaderProductionStatus {
            get {
                return ResourceManager.GetString("TableHeaderProductionStatus", resourceCulture);
            }
        }
        
        internal static string PageUserAllUsers {
            get {
                return ResourceManager.GetString("PageUserAllUsers", resourceCulture);
            }
        }
        
        internal static string PageUserNoUserFoun {
            get {
                return ResourceManager.GetString("PageUserNoUserFoun", resourceCulture);
            }
        }
        
        internal static string PageEditUserEditUser {
            get {
                return ResourceManager.GetString("PageEditUserEditUser", resourceCulture);
            }
        }
        
        internal static string PageEditUserNoUserFound {
            get {
                return ResourceManager.GetString("PageEditUserNoUserFound", resourceCulture);
            }
        }
        
        internal static string PageRegisterUserNewUser {
            get {
                return ResourceManager.GetString("PageRegisterUserNewUser", resourceCulture);
            }
        }
        
        internal static string PageProjectsOverviewAllProjects {
            get {
                return ResourceManager.GetString("PageProjectsOverviewAllProjects", resourceCulture);
            }
        }
        
        internal static string ButtonFilter {
            get {
                return ResourceManager.GetString("ButtonFilter", resourceCulture);
            }
        }
        
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        internal static string TableHeaderMonth {
            get {
                return ResourceManager.GetString("TableHeaderMonth", resourceCulture);
            }
        }
        
        internal static string TableHeaderYear {
            get {
                return ResourceManager.GetString("TableHeaderYear", resourceCulture);
            }
        }
        
        internal static string OptionAll {
            get {
                return ResourceManager.GetString("OptionAll", resourceCulture);
            }
        }
    }
}
