//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaEco.Abstractions.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesAbstractions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesAbstractions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SeaEco.Abstractions.Resources.ResourcesAbstractions", typeof(ResourcesAbstractions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ErrorMessageFirstNameRequired {
            get {
                return ResourceManager.GetString("ErrorMessageFirstNameRequired", resourceCulture);
            }
        }
        
        internal static string ErrorMessageFirstNameMinLength {
            get {
                return ResourceManager.GetString("ErrorMessageFirstNameMinLength", resourceCulture);
            }
        }
        
        internal static string ErrorMessageLastNameRequired {
            get {
                return ResourceManager.GetString("ErrorMessageLastNameRequired", resourceCulture);
            }
        }
        
        internal static string ErrorMessageMailError {
            get {
                return ResourceManager.GetString("ErrorMessageMailError", resourceCulture);
            }
        }
        
        internal static string ErrorMessageMailRequired {
            get {
                return ResourceManager.GetString("ErrorMessageMailRequired", resourceCulture);
            }
        }
        
        internal static string ErrorMessageLastNameMinLength {
            get {
                return ResourceManager.GetString("ErrorMessageLastNameMinLength", resourceCulture);
            }
        }
        
        internal static string ErrorMessageRepPasswordCompare {
            get {
                return ResourceManager.GetString("ErrorMessageRepPasswordCompare", resourceCulture);
            }
        }
        
        internal static string ErrorMessagePasswordRequired {
            get {
                return ResourceManager.GetString("ErrorMessagePasswordRequired", resourceCulture);
            }
        }
        
        internal static string ErrorMessageRepPasswordRequired {
            get {
                return ResourceManager.GetString("ErrorMessageRepPasswordRequired", resourceCulture);
            }
        }
        
        internal static string ErrorMessagePasswordMinLength {
            get {
                return ResourceManager.GetString("ErrorMessagePasswordMinLength", resourceCulture);
            }
        }
        
        internal static string ErrorMessagePasswordContain {
            get {
                return ResourceManager.GetString("ErrorMessagePasswordContain", resourceCulture);
            }
        }
    }
}
